# Generated by Django 5.1.6 on 2025-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('outcome', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.BooleanField(default=True)),
            ],
        ),
    ]
